<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="N700278" name="test ldg(failed)(failed)" tests="9" failures="3" timestamp="28 Jun 2016 21:59:46 GMT" time="413.051" errors="0">
  <testcase name="LdgTrailerWithoutProNoChange" time="8.303" classname="TestCase.LdgScreen.US2000119NewSubmitButtonLDG"/>
  <testcase name="LdgTrailerWithProChangeDestinationAddPRO" time="23.32" classname="TestCase.LdgScreen.US2000119NewSubmitButtonLDG"/>
  <testcase name="SetTrailerToLoadingNoShipments" time="33.721" classname="TestCase.LdgScreen.LDGTesting"/>
  <testcase name="LDGWithoutProChangeDestination" time="12.018" classname="TestCase.LdgScreen.LDGTesting">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [580]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [580]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestCase.LdgScreen.LDGTesting.LDGWithoutProChangeDestination(LDGTesting.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- LDGWithoutProChangeDestination -->
  <testcase name="LDGTrailerWithProChangeDestination" time="25.41" classname="TestCase.LdgScreen.LDGTesting"/>
  <testcase name="NoLdgEmptyTrailerAddNonExistingPro" time="21.594" classname="TestCase.LdgScreen.LDGTesting">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [730]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [730]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestCase.LdgScreen.LDGTesting.NoLdgEmptyTrailerAddNonExistingPro(LDGTesting.java:965)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- NoLdgEmptyTrailerAddNonExistingPro -->
  <testcase name="ldgTrailerWithoutProsClickNo" time="32.073" classname="TestCase.LdgScreen.US607PromptHeadloadOnDestinationChangeLDG"/>
  <testcase name="AddMultipleProsInSingleBatch" time="19.658" classname="TestCase.LdgScreen.US200075DisplayPROsInOrderWhichTheyEnter">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestCase.LdgScreen.US200075DisplayPROsInOrderWhichTheyEnter.AddMultipleProsInSingleBatch(US200075DisplayPROsInOrderWhichTheyEnter.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- AddMultipleProsInSingleBatch -->
  <testcase name="LdgTrailerWithoutProChangeDestinationAddPRO" time="27.986" classname="TestCase.LdgScreen.US200091SmartEnterLDG"/>
</testsuite> <!-- test ldg(failed)(failed) -->
