<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="N700278" name="test ldg2" tests="1" failures="1" timestamp="8 Jun 2016 19:12:07 GMT" time="195.202" errors="0">
  <testcase name="AddMultipleProsInSingleBatch" time="167.099" classname="trial.US200075DisplayPROsInOrderWhichTheyEnter">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Source_Create_ID is wrong expected [LH.LDG] but found [HRZ119],
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Source_Create_ID is wrong expected [LH.LDG] but found [HRZ119],
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at trial.US200075DisplayPROsInOrderWhichTheyEnter.AddMultipleProsInSingleBatch(US200075DisplayPROsInOrderWhichTheyEnter.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
]]>
    </failure>
  </testcase> <!-- AddMultipleProsInSingleBatch -->
</testsuite> <!-- test ldg2 -->
