<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N700278" name="LdgScreen.US452RemoveShipment" tests="4" failures="1" timestamp="16 Jun 2016 06:54:56 GMT" time="220.173" errors="0">
  <testcase name="VerifyDockPro" time="34.311" classname="LdgScreen.US452RemoveShipment">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [135],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [135]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [135],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [135]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at LdgScreen.US452RemoveShipment.VerifyDockPro(US452RemoveShipment.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- VerifyDockPro -->
  <testcase name="DockAndReAdd" time="127.304" classname="LdgScreen.US452RemoveShipment"/>
  <testcase name="VerifyDockThenAddNewPRO" time="26.051" classname="LdgScreen.US452RemoveShipment"/>
  <testcase name="EmptyTrailerAddSomeThenDock" time="32.507" classname="LdgScreen.US452RemoveShipment"/>
</testsuite> <!-- LdgScreen.US452RemoveShipment -->
