<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N700278" name="SitTest.US100002InquiryScreen" tests="4" failures="2" timestamp="10 Mar 2016 04:59:02 GMT" time="565.540" errors="0">
  <testcase name="Filter" time="196.514" classname="SitTest.US100002InquiryScreen">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	  OFD   40 Feet	  OFD   40 Feet: Lists differ at element [1]: [820294, 06/05  11:27, 40, P &amp; D, 6684] != [820294, 06/05  11:27, 40, P &amp; D, 6685] expected [[820294, 06/05  11:27, 40, P &amp; D, 6684]] but found [[820294, 06/05  11:27, 40, P &amp; D, 6685]]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	  OFD   40 Feet	  OFD   40 Feet: Lists differ at element [1]: [820294, 06/05  11:27, 40, P & D, 6684] != [820294, 06/05  11:27, 40, P & D, 6685] expected [[820294, 06/05  11:27, 40, P & D, 6684]] but found [[820294, 06/05  11:27, 40, P & D, 6685]]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:48)
	at SitTest.US100002InquiryScreen.Filter(US100002InquiryScreen.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- Filter -->
  <testcase name="Filter" time="185.857" classname="SitTest.US100002InquiryScreen"/>
  <testcase name="Filter" time="121.901" classname="SitTest.US100002InquiryScreen"/>
  <testcase name="Filter" time="61.268" classname="SitTest.US100002InquiryScreen">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	  ARV   45 Feet	  ARV   45 Feet: Lists differ at element [0]: [8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29530] != [8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29531] expected [[8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29530]] but found [[8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29531]]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	  ARV   45 Feet	  ARV   45 Feet: Lists differ at element [0]: [8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29530] != [8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29531] expected [[8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29530]] but found [[8162, 10/26  13:34, 107, 45, STORAGE EQUIP, 29531]]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:48)
	at SitTest.US100002InquiryScreen.Filter(US100002InquiryScreen.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- Filter -->
</testsuite> <!-- SitTest.US100002InquiryScreen -->
